apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python-solar-forecast
  namespace: api
  labels:
    app: api-python-solar-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-python-solar-forecast
  template:
    metadata:
      labels:
        app: api-python-solar-forecast
    spec:
      containers:
      - name: api-python-solar-forecast
        image: railnlays/api-python-solar-forecast:latest
        ports:
        - containerPort: 5000
        env:
        - name: WORKERS
          value: "1"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1200Mi"
            cpu: "500m"
          limits:
            memory: "1400Mi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /healthzReadiness
            port: 5000
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthzLiveness
            port: 5000
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /healthzStartup
            port: 5000
          failureThreshold: 10
          periodSeconds: 10