apiVersion: v1
kind: Service
metadata:
  name: api-python-solar-forecast
  namespace: api
spec:
  type: LoadBalancer
  selector:
    app: api-python-solar-forecast
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP